# Generated by Django 5.2 on 2025-05-20 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Italy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='italy',
            options={'ordering': ['-time_create', 'title'], 'verbose_name': 'Italy', 'verbose_name_plural': 'Italy'},
        ),
        migrations.AddField(
            model_name='italy',
            name='p',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
