# Generated by Django 5.2 on 2025-05-20 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Italy', '0002_alter_italy_options_italy_p'),
    ]

    operations = [
        migrations.AddField(
            model_name='italy',
            name='content2',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='italy',
            name='photo',
            field=models.ImageField(upload_to='photo/%Y/%m/%d/'),
        ),
    ]
